version: "3.9"

services:
  web:
    build:
      context: ./chessboard
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./chessboard/.env