# Generated by Django 4.0.3 on 2022-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.IntegerField(
                        choices=[(1, 'Knight'), (2, 'Other piece')]
                    ),
                ),
                (
                    'color',
                    models.IntegerField(choices=[(1, 'Black'), (2, 'White')]),
                ),
            ],
            options={
                'verbose_name': 'Piece',
                'verbose_name_plural': 'Pieces',
            },
        ),
    ]
